/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Controladores.ControladorPrincipal;


/**
 *
 * @author Valentina
 */
public class VentanaMenuAdminFlota extends javax.swing.JFrame {

    /**
     * Creates new form VentanaMenuAdminFlota
     */
    
    private ControladorPrincipal controladorPrincipal;
    
    public VentanaMenuAdminFlota(ControladorPrincipal controladorPrincipal) {
        initComponents();
        this.controladorPrincipal = controladorPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuses = new javax.swing.JButton();
        btnViajes = new javax.swing.JButton();
        btnVentaTiquetes = new javax.swing.JButton();
        bntVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBuses.setText("Gestion buses");
        btnBuses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusesActionPerformed(evt);
            }
        });

        btnViajes.setText("Gestion viajes");
        btnViajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViajesActionPerformed(evt);
            }
        });

        btnVentaTiquetes.setText("Venta tiquetes");
        btnVentaTiquetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaTiquetesActionPerformed(evt);
            }
        });

        bntVolver.setText("Volver");
        bntVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bntVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuses)
                        .addGap(18, 18, 18)
                        .addComponent(btnViajes)
                        .addGap(18, 18, 18)
                        .addComponent(btnVentaTiquetes, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuses)
                    .addComponent(btnViajes)
                    .addComponent(btnVentaTiquetes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(bntVolver)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntVolverActionPerformed
        // TODO add your handling code here:
        VistaLogin login = new VistaLogin(controladorPrincipal);
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bntVolverActionPerformed

    private void btnViajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViajesActionPerformed
        // TODO add your handling code here:
        VentanaGestionViajes viajes = new VentanaGestionViajes(controladorPrincipal);
        viajes.setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_btnViajesActionPerformed

    private void btnBusesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusesActionPerformed
        // TODO add your handling code here:
        VentanaGestionBuses buses = new  VentanaGestionBuses(controladorPrincipal);
        buses.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBusesActionPerformed

    private void btnVentaTiquetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaTiquetesActionPerformed
        // TODO add your handling code here:
        VentanaVentaTiquetes venta = new VentanaVentaTiquetes(controladorPrincipal);
        venta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVentaTiquetesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntVolver;
    private javax.swing.JButton btnBuses;
    private javax.swing.JButton btnVentaTiquetes;
    private javax.swing.JButton btnViajes;
    // End of variables declaration//GEN-END:variables
}
