/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Controladores.ControladorCaseta;
import Controladores.ControladorPrincipal;
import Excepciones.EmailValidoException;
import Excepciones.TelefonoValidoException;
import Modelo.AdminFlota;
import Modelo.Caseta;
import Util.Utils;
import javax.swing.JOptionPane;

/**
 *
 * @author Valentina
 */
public class VentanaAsignarCaseta extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAsignarCaseta
     */
    
    private ControladorPrincipal controladorPrincipal;
    private ControladorCaseta controladorCaseta;
    private Utils util = new Utils();
    
    public VentanaAsignarCaseta(ControladorPrincipal controladorPrincipal, Caseta caseta) {
        initComponents();
        this.controladorPrincipal = controladorPrincipal;
        this.controladorCaseta = new ControladorCaseta(caseta, controladorPrincipal.getTerminal());
        this.verInformacion(caseta);
    }
    
    private void verInformacion(Caseta caseta){
        
        if(caseta.getAdminFlota() != null){
            txtCedula.setText(caseta.getAdminFlota().getCedula());
            txtNombre.setText(caseta.getAdminFlota().getNombre());
            txtEdad.setText(caseta.getAdminFlota().getEdad()+"");
            txtCorreo.setText(caseta.getAdminFlota().getCorreo());
            txtTelefono.setText(caseta.getAdminFlota().getNumTel());
            txtSueldo.setText(caseta.getAdminFlota().getSueldo()+"");
            txtContrasena.setText(caseta.getAdminFlota().getContraseña());

            txtNit.setText(caseta.getNit());
            txtNombreEmpresa.setText(caseta.getNombreEmpresa());
            txtValorArrendamiento.setText(caseta.getValorCanonArrendamiento()+"");
            txtCantidad.setText(caseta.getCantidadPlazasEstacionamiento()+"");
            txtTelefonoEmpresa.setText(caseta.getAdminFlota().getTelefonoEmpresa());
        }
    }
    
    private boolean validarCampos() {
        String cedula = txtCedula.getText();
        String nombre = txtNombre.getText();
        String edad = txtEdad.getText();
        String correo = txtCorreo.getText();
        String telefono = txtTelefono.getText();
        String sueldo = txtSueldo.getText();
        String contrasena = txtContrasena.getText();
        
        String nit = txtNit.getText();
        String nombreEmpresa = txtNombreEmpresa.getText();
        String valorArrendamiento = txtValorArrendamiento.getText();
        String cantidadPlazas = txtCantidad.getText();
        String telefonoEmpresa = txtTelefonoEmpresa.getText();

        if (cedula.trim().equals("") || nombre.trim().equals("") || edad.trim().equals("") || correo.trim().equals("") || telefono.trim().equals("")
                || sueldo.trim().equals("") || contrasena.trim().equals("") || nit.trim().equals("") || nombreEmpresa.trim().equals("")
                || valorArrendamiento.trim().equals("") || cantidadPlazas.trim().equals("") || telefonoEmpresa.trim().equals("")) {
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCedula = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtContrasena = new javax.swing.JTextField();
        txtSueldo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txtCantidad = new javax.swing.JTextField();
        txtNit = new javax.swing.JTextField();
        txtNombreEmpresa = new javax.swing.JTextField();
        txtValorArrendamiento = new javax.swing.JTextField();
        txtTelefonoEmpresa = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        btnVolver2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Administrador flota"));

        txtCedula.setBorder(javax.swing.BorderFactory.createTitledBorder("Cedula"));

        txtNombre.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));

        txtEdad.setBorder(javax.swing.BorderFactory.createTitledBorder("Edad"));

        txtCorreo.setBorder(javax.swing.BorderFactory.createTitledBorder("Email"));

        txtTelefono.setBorder(javax.swing.BorderFactory.createTitledBorder("Telefono"));

        txtContrasena.setBorder(javax.swing.BorderFactory.createTitledBorder("Contraseña"));

        txtSueldo.setBorder(javax.swing.BorderFactory.createTitledBorder("Sueldo"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                        .addComponent(txtCedula, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos empresa"));

        txtCantidad.setBorder(javax.swing.BorderFactory.createTitledBorder("Cant plazas estacionamiento"));

        txtNit.setBorder(javax.swing.BorderFactory.createTitledBorder("NIT"));

        txtNombreEmpresa.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));

        txtValorArrendamiento.setBorder(javax.swing.BorderFactory.createTitledBorder("Valor arrendamiento"));

        txtTelefonoEmpresa.setBorder(javax.swing.BorderFactory.createTitledBorder("Telefono"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtNit, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
            .addComponent(txtNombreEmpresa)
            .addComponent(txtValorArrendamiento)
            .addComponent(txtCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
            .addComponent(txtTelefonoEmpresa)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txtNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtValorArrendamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTelefonoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        btnCrear.setText("Registrar");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnVolver2.setText("Volver");
        btnVolver2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolver2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVolver2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(btnVolver2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:

        if(validarCampos()){

            String cedula = txtCedula.getText();
            String nit = txtNit.getText();

            if(controladorCaseta.verificarExistenciaAdminFlota(cedula)){
                JOptionPane.showMessageDialog(null, "Este administrador de flota ya esta trabajando para una empresa");
                return;
            }

            if(controladorCaseta.verificarExistenciaEmpresa(nit)){
                JOptionPane.showMessageDialog(null, "Esta empresa ya se encuentra registrada en la terminal");
                return;
            }

            try {
                String nombre = txtNombre.getText();
                String anos = txtEdad.getText();
                int edad = Integer.parseInt(anos);
                String correo = txtCorreo.getText();
                String telefono = txtTelefono.getText();
                String salario = txtSueldo.getText();
                double sueldo = Double.parseDouble(salario);
                String contrasena = txtContrasena.getText();

                String nombreEmpresa = txtNombreEmpresa.getText();
                String valorArrendamiento = txtValorArrendamiento.getText();
                double valorArrenda = Double.parseDouble(valorArrendamiento);
                String cantidadPlazas = txtCantidad.getText();
                int cantidad = Integer.parseInt(cantidadPlazas);
                String telefonoEmpresa = txtTelefonoEmpresa.getText();
                String tipoUsuario = "ADMIN_FLOTA";
            
                util.validarEmail(correo);
                util.validarTelefono(telefono);
                util.validarTelefono(telefonoEmpresa);
                
                AdminFlota adminFlota = new AdminFlota(sueldo, telefonoEmpresa, edad, nombre, cedula, correo, telefono , tipoUsuario, contrasena);
                controladorCaseta.guardarDatosCaseta(adminFlota, nit, nombreEmpresa, valorArrenda, cantidad);
                controladorPrincipal.guardarCambios();
                JOptionPane.showMessageDialog(null, "Se guardaron los datos de la caseta exitosamente");
                
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Ingrese un numero valido");
            }
            catch (TelefonoValidoException | EmailValidoException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }else{
            JOptionPane.showMessageDialog(null, "todos los campos son obligatorios");
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnVolver2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver2ActionPerformed
        // TODO add your handling code here:
        VentanaCasetas vc = new VentanaCasetas(controladorPrincipal);
        vc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolver2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnVolver2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtContrasena;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNit;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreEmpresa;
    private javax.swing.JTextField txtSueldo;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefonoEmpresa;
    private javax.swing.JTextField txtValorArrendamiento;
    // End of variables declaration//GEN-END:variables
}
