/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Controladores.ControladorGestionViajes;
import Controladores.ControladorPrincipal;
import Excepciones.BusInhabilitadoException;
import Excepciones.FormatoFechaException;
import Modelo.Bus;
import Modelo.Caseta;
import Modelo.Usuario;
import Modelo.Viaje;
import Util.Lista;
import Util.Utils;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Valentina
 */
public class VentanaGestionViajes extends javax.swing.JFrame {

    /**
     * Creates new form VentanaGestionViajes
     */
    
    private ControladorPrincipal controladorPrincipal;
    private ControladorGestionViajes controladorGestionViajes;
    private Usuario usuarioLogueado = null;
    private Utils util = new Utils();
    
    public VentanaGestionViajes(ControladorPrincipal controladorPrincipal) {
        initComponents();
        this.controladorPrincipal = controladorPrincipal;
        usuarioLogueado = this.controladorPrincipal.getUsuariologin();
        Caseta caseta = controladorPrincipal.buscarCaseta(usuarioLogueado.getCedula());
        this.controladorGestionViajes = new ControladorGestionViajes(caseta);
        
        txtOrigen.setText(controladorPrincipal.getCiudadTerminal());
        txtOrigen.setEnabled(false);
        llenarTabla();
        llenarComboBus();
    }
    
    private void llenarComboBus(){
        Lista<Bus> lista = controladorGestionViajes.getListaBuses();
        for (int i = 0; i < lista.size(); i++) {
            cbBus.addItem(lista.get(i));
        }
    }
    
    private void llenarTabla() {
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{"Origen", "Destino", "Fecha Salida", "Fecha Llegada", "Valor unitario", "Placa Bus"});
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
        Lista<Viaje> lista = controladorGestionViajes.getListaViajes();
        for (int i = 0; i < lista.size(); i++) {
            Viaje viaje = lista.get(i);
            model.addRow(new Object[]{
                viaje.getOrigen(),
                viaje.getDestino(),
                viaje.getFechaSalidaCompleta().format(formatter),
                viaje.getFechaLlegadaCompleta().format(formatter),
                viaje.getValorUnitario(),
                viaje.getBus().getPlaca()
            });
        }
        tabla.setModel(model);
    }
    
    private boolean validarCampos() { 
        String destino = txtDestino.getText();
        String fechaSalida = txtSalida.getText();
        String fechaLlegada = txtLlegada.getText();
        String valor = txtValor.getText();
        Bus bus = (Bus) cbBus.getSelectedItem();
        
        if (destino.trim().equals("") || fechaSalida.trim().equals("") || fechaLlegada.trim().equals("")
                || valor.trim().equals("") || bus == null) {
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSalida = new javax.swing.JTextField();
        txtOrigen = new javax.swing.JTextField();
        txtDestino = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        txtLlegada = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        cbBus = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btnVolver = new javax.swing.JButton();
        cbHoraLlegada = new javax.swing.JComboBox<>();
        cbHoraSalida = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtSalida.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha salida"));

        txtOrigen.setBorder(javax.swing.BorderFactory.createTitledBorder("Origen"));

        txtDestino.setBorder(javax.swing.BorderFactory.createTitledBorder("Destino"));

        txtValor.setBorder(javax.swing.BorderFactory.createTitledBorder("Valor unitario"));

        txtLlegada.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha llegada"));

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        cbBus.setBorder(javax.swing.BorderFactory.createTitledBorder("Bus"));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        cbHoraLlegada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        cbHoraLlegada.setBorder(javax.swing.BorderFactory.createTitledBorder("Hora llegada"));

        cbHoraSalida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        cbHoraSalida.setBorder(javax.swing.BorderFactory.createTitledBorder("Hora salida"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtDestino)
                                .addComponent(txtSalida)
                                .addComponent(txtOrigen)
                                .addComponent(cbBus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtLlegada)
                                .addComponent(cbHoraSalida, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbHoraLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(txtOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(cbHoraLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbBus, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCrear)
                            .addComponent(btnVolver))))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        VentanaMenuAdminFlota vmaf = new VentanaMenuAdminFlota(controladorPrincipal);
        vmaf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
        
        if(validarCampos()){
            
            String origen = txtOrigen.getText();
            String destino = txtDestino.getText();
            String fechaSalida = txtSalida.getText();
            String fechaLlegada = txtLlegada.getText();
            String valor = txtValor.getText();
            Bus bus = (Bus) cbBus.getSelectedItem();
            String horaSalida = (String) cbHoraSalida.getSelectedItem();
            String horaLlegada = (String) cbHoraLlegada.getSelectedItem();
            
            try {
                util.validarFecha(fechaSalida);
                util.validarFecha(fechaLlegada);
                
                boolean esFechaMayorSalida = util.fechaMayorAlSistema(fechaSalida, horaSalida);
                boolean esFechaMayorLlegada = util.fechaMayorAlSistema(fechaLlegada, horaLlegada);
                if(!esFechaMayorSalida || !esFechaMayorLlegada){
                    JOptionPane.showMessageDialog(null, "Las fechas deben tener una fecha mayor a la actual");
                    return;
                }
                
                if(!util.esFechaInicioMenor(fechaSalida, horaSalida, fechaLlegada, horaLlegada)){
                    JOptionPane.showMessageDialog(null, "Las fecha de salida debe de ser menor a la fecha llegada");
                    return;
                }
                
                Double valorUnitario = Double.parseDouble(valor);
                Viaje viaje = new Viaje(origen, destino, fechaSalida, fechaLlegada, horaSalida, horaLlegada, bus, valorUnitario);
                controladorGestionViajes.agregarViaje(viaje);
                controladorPrincipal.guardarCambios();
                llenarTabla();
                JOptionPane.showMessageDialog(null, "El viaje se registro");
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Ingrese un numero valido");
            } catch (FormatoFechaException | BusInhabilitadoException ex) {
               JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }else{
            JOptionPane.showMessageDialog(null, "todos los campos son obligatorios");
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<Bus> cbBus;
    private javax.swing.JComboBox<String> cbHoraLlegada;
    private javax.swing.JComboBox<String> cbHoraSalida;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtLlegada;
    private javax.swing.JTextField txtOrigen;
    private javax.swing.JTextField txtSalida;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
